functionsDirectory = "/Users/angietatianapena/TWAI-PERXIA-DEMO/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/angietatianapena/TWAI-PERXIA-DEMO/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/angietatianapena/TWAI-PERXIA-DEMO/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/api/auth/*"
to = "/.netlify/functions/auth/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/auth"
to = "/.netlify/functions/auth"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]